### ISSUE TITLE
What are you using for background tasks? You are not using coroutines or rx?

### ISSUE THREAD

**Issue by donenoyes** [commonpepper/Photosen#5]
Thank You. Love your app.

**Comment by commonpepper** [comment]
Hi @jiayounokim! I just use [Retrofit](https://square.github.io/retrofit/) for all communications with Flickr API. Also there is [InterntService](https://github.com/commonpepper/Photosen/blob/master/app/src/main/java/com/commonpepper/photosen/network/DownloadService.kt) for downloading the source photo. No coroutines or rxjava as I remember :)
